name: SSH Login 

on: [push]

jobs:
  ssh:

    runs-on: ubuntu-latest

    steps:
   
    - name: SSH Login
      run: |
        sshpass -p fsdfdsfdsf -t -t stagebo@18.203.21.215
        ls -la
      env:
        staging_pass: ${{ secrets.STAGING_PASS }}   

